# Site settings
title: \@grez dot net
email: devel@agrez.net
description: > # this means to ignore newlines until "baseurl:"
  Nothing much to see here yet!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agrez.net" # the base hostname & protocol for your site
twitter_username: fedberry_remix
github_username:  agrez

# Build settings
markdown: kramdown
