# Site settings
title: agrez.net
email: devel@agrez.net
description: > # this means to ignore newlines until "baseurl:"
  Powered by inquisitiveness, boredom & coffee
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agrez.net" # the base hostname & protocol for your site
twitter_username: fedberry_remix
github_username:  agrez

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
